### ISSUE TITLE
ModuleNotFoundError: No module named 'thesaurus.models'

### ISSUE THREAD

**Issue by idrissbachali** [opensemanticsearch/open-semantic-visual-graph-explorer#26]
there is a problem when i need to use thesaurus !!!
python doesn't recognize facet as a library 

please can u help me? it's really important.

**Comment by opensemanticsearch** [comment]
This model is part of https://github.com/opensemanticsearch/open-semantic-search-apps where all Django apps that are needed are installed in Django environment ...

Has to be loaded more dynamic / only if installed in futrue.
