### ISSUE TITLE
Selector/Filter for classes/properties/facets

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-visual-graph-explorer#6]
Selector to filter by different classes/properties/facets.

**Comment by Mandalka** [comment]
Selectors for facets, classes and properties are available in search UI view connections (graph).

To add for custom extension/loading connections of a node.

**Comment by Mandalka** [comment]
Extension of graph loading now loads only selected classes/facets/types/properties.
